plugins {
    id 'java'
    id 'idea'
    id 'maven-publish'

    id "me.shedaniel.unified-publishing" version "0.1.+"

    id "net.neoforged.moddev.legacyforge" version "2.0.115"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(java_version.toInteger())
java.withSourcesJar()

sourceSets.main.resources.srcDirs += "src/main/generated"

group = 'wootrevived'
def buildVersion = "${mod_version}"
version = "${mc_version}-${buildVersion}"

base {
    archivesName = "woot-revived"
}

legacyForge {
    enable { neoForgeVersion = "${mc_version}-${neo_version}" }

    runs {
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG

            jvmArguments.addAll "-Dmixin.debug=true", "-Dmixin.checks.interfaces=true", "-Dmixin.debug.export=true"
        }

        client {
            client()

            gameDirectory = file('runs/client')

            systemProperty "guideme.woot_revived.guide.sources", file("src/main/resources/assets/woot_revived/guidebook").getAbsolutePath()
            systemProperty "guideme.woot_revived.guide.sourcesNamespace", "woot_revived"
        }

        data {
            data()

            gameDirectory = file('runs/data')

            programArguments.addAll '--mod', mod_id, '--all', '--output', file('src/main/generated/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        server {
            server()

            gameDirectory = file('runs/server')

            programArgument '--nogui'
        }
    }

    mods {
        woot_revived {
            sourceSet sourceSets.main
        }
    }
}

mixin {
    config 'woot_revived.mixins.json'
}

def refmapFile = mixin.add(sourceSets.main, 'woot_revived.mixins.refmap.json')

tasks.withType(ProcessResources).configureEach {
    dependsOn tasks.named('compileJava')

    from(refmapFile) { into '' }

    var replaceProperties = [
            mod_id            : mod_id,
            mod_name          : mod_name,
            mod_version       : mod_version,
            mc_version        : mc_version,
            neo_version       : neo_version,
            guideme_version   : guideme_version,
            jei_version       : jei_version,
            jade_version      : jade_version,
            kubejs_version    : kubejs_version,
            neo_major_version : neo_version.split('\\.')[0]
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml']) {
        expand replaceProperties
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = "https://maven.neoforged.net/releases" }
    maven { url = "https://maven.minecraftforge.net/" }
    maven { url = "https://maven.blamejared.com/" }
    maven { url = "https://maven.creeperhost.net" }
    maven { url = "https://maven.architectury.dev" }
    maven { url = "https://api.modrinth.com/maven" }
}

dependencies {
    annotationProcessor "org.spongepowered:mixin:0.8.5:processor"

    compileOnly 'org.jetbrains:annotations:22.0.0'

    // JEI
    modCompileOnly "mezz.jei:jei-${mc_version}-common-api:${jei_version}"
    modCompileOnly "mezz.jei:jei-${mc_version}-forge-api:${jei_version}"
    modRuntimeOnly "mezz.jei:jei-${mc_version}-forge:${jei_version}"

    // Jade
    modImplementation "maven.modrinth:jade:${jade_version}"

    // GuideME
    modCompileOnly "org.appliedenergistics:guideme:${guideme_version}:api"
    modRuntimeOnly "org.appliedenergistics:guideme:${guideme_version}"

    // KubeJS
    modImplementation "dev.architectury:architectury-forge:${architectury_version}"
    modImplementation "maven.modrinth:kubejs:${kubejs_version}+forge"
    modImplementation "maven.modrinth:rhino:${rhino_version}+forge"

    // Optimizations
    modRuntimeOnly "maven.modrinth:ferrite-core:${ferritecore_version}"
}

jar {
    exclude '.cache/**'

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    manifest {
        attributes([
                'Specification-Title'     : "${mod_name}",
                'Specification-Vendor'    : 'pharuxtan',
                'Specification-Version'   : "${mc_version}",
                'Implementation-Title'    : "${mod_id}",
                'Implementation-Vendor'   : 'pharuxtan',
                'Implementation-Version'  : "${mod_version}",
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                'MixinConfigs'            : 'woot_revived.mixins.json'
        ])
    }
}

tasks.register('apiJar', Jar) {
    archiveClassifier = 'api'

    from(sourceSets.main.output) {
        include 'wootrevived/api/**'
    }

    exclude 'woot_revived.mixins.refmap.json'

    manifest {
        attributes([
                'Specification-Title'     : "${mod_name} API",
                'Specification-Vendor'    : 'pharuxtan',
                'Specification-Version'   : "${mc_version}",
                'Implementation-Title'    : "${mod_id}",
                'Implementation-Vendor'   : 'pharuxtan',
                'Implementation-Version'  : "api-${mod_version}",
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

tasks.register('apiSourcesJar', Jar) {
    dependsOn classes
    archiveClassifier = 'api-sources'

    from(sourceSets.main.allSource) {
        include 'wootrevived/api/**'
    }

    manifest {
        attributes([
                'Specification-Title'     : "${mod_name} API",
                'Specification-Vendor'    : 'pharuxtan',
                'Specification-Version'   : "${mc_version}",
                'Implementation-Title'    : "${mod_id}",
                'Implementation-Vendor'   : 'pharuxtan',
                'Implementation-Version'  : "api-${mod_version}",
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

tasks.assemble {
    dependsOn tasks.named('apiJar')
    dependsOn tasks.named('apiSourcesJar')
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += ['-Xlint:deprecation', '-Xlint:unchecked']
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
