plugins {
    id 'java'
    id 'idea'
    id 'maven-publish'

    id 'com.github.johnrengelman.shadow' version '7.1.2'
    id 'com.matthewprenger.cursegradle' version '1.4.0'
    id 'com.modrinth.minotaur' version "2.+"

    id 'net.neoforged.gradle' version '6.0.21'
    id 'org.spongepowered.mixin' version '0.7.+'
}

java.toolchain.languageVersion = JavaLanguageVersion.of("${java_version}")
java.withSourcesJar()

sourceSets.main.resources.srcDirs += "src/main/generated"

group = 'wootrevived'
archivesBaseName = "woot-revived"
def buildVersion = "${mod_version}"
version = "${mc_version}-${buildVersion}"

minecraft {
    mappings channel: 'official', version: "${mc_version}"

    runs {
        configureEach {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${buildDir}/createSrgToMcp/output.srg"

            args '-mixin.config=woot_revived.mixins.json'

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        client {
            property 'forge.enabledGameTestNamespaces', mod_id

            property "guideme.woot_revived.guide.sources", file("src/main/resources/assets/woot_revived/guidebook").absolutePath
            property "guideme.woot_revived.guide.sourcesNamespace", "woot_revived"
        }

        server {
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--nogui'
        }

        gameTestServer {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        data {
            workingDirectory project.file('run-data')

            args '--mod', mod_id, '--all', '--output', file('src/main/generated/'), '--existing', file('src/main/resources/')
        }
    }
}

mixin {
    add sourceSets.main, 'woot_revived.mixins.refmap.json'
    config 'woot_revived.mixins.json'
}

processResources {
    filesMatching('META-INF/mods.toml') {
        expand 'file': [
                        'modId': mod_id,
                        'jarVersion': mod_version
                ],
                'mc_version': mc_version,
                'neo_version': neo_version,
                'guideme_version': guideme_version,
                'jei_version': jei_version,
                'jade_version': jade_version,
                'kubejs_version': kubejs_version,
                'neo_major_version': neo_version.split('\\.')[0]
    }
}

configurations {
    annotationProcessor.extendsFrom minecraft
    shadowIn
    implementation.extendsFrom shadowIn
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = "https://maven.neoforged.net/releases" }
    maven { url = "https://maven.minecraftforge.net/" }
    maven { url = "https://maven.blamejared.com/" }
    maven { url = "https://maven.creeperhost.net" }
    maven { url = "https://maven.architectury.dev" }
    maven { url = "https://api.modrinth.com/maven" }
}

dependencies {
    minecraft "net.neoforged:forge:${mc_version}-${neo_version}"

    compileOnly 'org.jetbrains:annotations:22.0.0'

    // JEI
    compileOnly fg.deobf("mezz.jei:jei-${mc_version}-common-api:${jei_version}")
    compileOnly fg.deobf("mezz.jei:jei-${mc_version}-forge-api:${jei_version}")
    runtimeOnly fg.deobf("mezz.jei:jei-${mc_version}-forge:${jei_version}")

    // Jade
    implementation fg.deobf("maven.modrinth:jade:${jade_version}")

    // GuideME
    compileOnly fg.deobf("org.appliedenergistics:guideme:${guideme_version}:api")
    runtimeOnly fg.deobf("org.appliedenergistics:guideme:${guideme_version}")

    // KubeJS
    implementation fg.deobf("dev.architectury:architectury-forge:${architectury_version}")
    implementation fg.deobf("maven.modrinth:kubejs:${kubejs_version}+forge")
    implementation fg.deobf("maven.modrinth:rhino:${rhino_version}+forge")

    // Optimizations
    runtimeOnly fg.deobf("org.embeddedt:embeddium-${mc_version}:${embeddium_version}")
    runtimeOnly fg.deobf("maven.modrinth:modernfix:${modernfix_version}")
    runtimeOnly fg.deobf("maven.modrinth:ferrite-core:${ferritecore_version}")
}

shadowJar {
    finalizedBy 'reobfShadowJar'
    archiveClassifier = ''
    manifest {
        attributes([
                'Specification-Title'     : "${mod_name}",
                'Specification-Vendor'    : 'pharuxtan',
                'Specification-Version'   : "${mc_version}",
                'Implementation-Title'    : "${mod_id}",
                'Implementation-Vendor'   : 'pharuxtan',
                'Implementation-Version'  : "${mod_version}",
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                'MixinConfigs'            : 'woot_revived.mixins.json'
        ])
    }
    configurations = [project.configurations.shadowIn]

    doFirst {
        exclude '.cache/**'
    }
}

tasks.register('apiJar', Jar) {
    finalizedBy 'apiSourcesJar'
    finalizedBy 'reobfApiJar'

    archiveClassifier = 'api'

    from(sourceSets.main.output) {
        include 'wootrevived/api/**'
    }

    manifest {
        attributes([
                'Specification-Title'     : "${mod_name} API",
                'Specification-Vendor'    : 'pharuxtan',
                'Specification-Version'   : "${mc_version}",
                'Implementation-Title'    : "${mod_id}",
                'Implementation-Vendor'   : 'pharuxtan',
                'Implementation-Version'  : "api-${mod_version}",
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }

    doFirst {
        exclude 'woot_revived.mixins.refmap.json'
    }
}

tasks.register('apiSourcesJar', Jar) {
    dependsOn classes
    archiveClassifier = 'api-sources'

    from(sourceSets.main.allSource) {
        include 'wootrevived/api/**'
    }

    manifest {
        attributes([
                'Specification-Title'     : "${mod_name} API Sources",
                'Specification-Vendor'    : 'pharuxtan',
                'Specification-Version'   : "${mc_version}",
                'Implementation-Title'    : "${mod_id}",
                'Implementation-Vendor'   : 'pharuxtan',
                'Implementation-Version'  : "api-${mod_version}",
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

reobf {
    shadowJar {}
    apiJar {}
    jar { enabled = false }
}

jar.enabled = false

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += ['-Xlint:deprecation', '-Xlint:unchecked']
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
