modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/wootrevived/wootrevived/issues"
license = "LGPLv3"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/wootrevived/wootrevived"
logoFile = "woot_revived.png"
authors = "pharuxtan"
credits = "Ipsis"
description = '''A formidable multiblock mod to harvest mob drops. You'll either fall in love or despise it! No middle ground.'''

[[mixins]]
config = "woot_revived.mixins.json"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[${mc_version}]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId="guideme"
type = "required"
versionRange = "[${guideme_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
type = "optional"
versionRange = "[${jei_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="jade"
type = "optional"
versionRange = "[${jade_version},)"
ordering="NONE"
side="CLIENT"
